### ISSUE TITLE
Add quiet / exit code option

### ISSUE THREAD

**Issue by alexjurkiewicz** [fatih/hclfmt#11]
I'd like to use hclfmt to ensure my files are correctly formatted before committing changes to my repo. It would be nice if hclfmt would have an option which simply checks if a file has "incorrect" formatting and exits 1 if so (0 if everything is fine). eg `hclfmt -q main.tf`

Currently I can work around this issue by diffing the output against the source file, but this is a little painful.

**Comment by fatih** [comment]
Hi @alexjurkiewicz 

Thanks for the suggestion. The problem is that we can't detect an "incorrect" before writing. There is no incorrect things. If you run it, it'll successfully format it. If not it'll return with exit status 1 already. So I think this would be good enough. Thanks. Let me know if you think this is not sufficient.
